language: python
python:
  - "2.7"
sudo: false
cache:
  apt: true
  directories:
  - $HOME/.pip-cache
  - $HOME/.ccache
addons:
  apt:
    packages:
    - ccache
    - cmake
    - g++
    - gdb
    - graphviz
    - libboost-filesystem-dev
    - libgoogle-perftools-dev
    - libprotobuf-dev
    - libssl-dev
    - libtbb-dev
    - libzmq3-dev
    - make
    - p7zip-full
    - protobuf-compiler
    - python-pip
    - python-protobuf
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt
before_script:
  - export MAKEFLAGS="-j 2 -S"
  - export POMAGMA_DIFFTOOL=diff
  - g++ --version
  - cmake --version
  - ccache --version
  - python --version
  - pip freeze
  - env
  - ulimit -c
  - ulimit -c unlimited || echo 'Failed to set core file size'
script:
  - make small-test
