language: python
python:
  - 2.7
cache:
  apt: true
  directories:
  - $HOME/.pip-cache
virtualenv:
  system_site_packages: true
before_install:
  - export MAKEFLAGS="-j 2 -S"
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
install:
  - . install.sh
  - pip freeze
script:
  - make unit-test
