sudo: false
language: python
python:
  - "2.7"
addons:
  apt:
    sources:
      - ppa:chris-lea/node.js
    packages:
      - ccache
      - cmake
      - cscope
      - ctags
      - g++
      - gdb
      - graphviz
      - libboost-filesystem-dev
      - libhdf5-serial-dev
      - libprotobuf-dev
      - libssl-dev
      - libtbb-dev
      - libzmq-dev
      - make
      - nodejs
      - p7zip-full
      - protobuf-compiler
      - python-pip
      - python-protobuf
      - python-tables
      - virtualenvwrapper
cache:
  apt: true
  directories:
  - $HOME/.pip-cache
  - $HOME/.ccache
virtualenv:
  system_site_packages: true
before_install:
  # - sudo rm /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
  - export PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - pip install -r requirements.txt
  - export MAKEFLAGS="-j 2 -S"
install:
  - g++ --version
  - cmake --version
  - ccache --version
  - python --version
  - pip freeze
  - env
  - ulimit -c
  - make protobuf
  - pip install -e .
before_script:
  - ulimit -c unlimited || echo 'Failed to set core file size'
script:
  - make small-test
