language: python
compiler:
  - gcc
python:
  - "2.7"
node_js:
  - "0.10"
cache:
  apt: true
  directories:
  - $HOME/.pip-cache
virtualenv:
  system_site_packages: true
before_install:
  - export PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - pip install nose mock pep8 pyflakes simplejson pyzmq parsable boto
  - export MAKEFLAGS="-j 2 -S"
install:
  - . install.sh
  - pip freeze
script:
  - make unit-test
