name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: |
          vcpkg
          vcpkg_installed
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-
    
    - name: Cache ccache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-
    
    - name: Cache uv
      uses: actions/cache@v3
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-${{ matrix.python-version }}-
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Run installation script
      run: |
        chmod +x install.sh
        ./install.sh
    
    - name: Set up environment
      run: |
        echo "MAKEFLAGS=-j 2 -S" >> $GITHUB_ENV
        echo "POMAGMA_DIFFTOOL=diff" >> $GITHUB_ENV
        echo "CI=1" >> $GITHUB_ENV
        # Enable core dumps for debugging
        ulimit -c unlimited || echo 'Failed to set core file size'
    
    - name: Display versions
      run: |
        source ./env.sh
        source .venv/bin/activate
        clang++ --version
        cmake --version
        ccache --version
        python --version
        uv pip freeze
    
    - name: Run tests
      run: |
        source ./env.sh
        source .venv/bin/activate
        make small-test 